server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

        - id: candidate-service
          uri: lb://CANDIDATE-SERVICE
          predicates:
            - Path=/candidates/**
          filters:
            - AuthenticationFilter

        - id: employer-service
          uri: lb://EMPLOYER-SERVICE
          predicates:
            - Path=/employers/**
          filters:
            - AuthenticationFilter

  application:
    name: api-gateway
  jetty:
    threads:
      max: '1000'
  tomcat:
    threads:
      max: '1000'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"
# Actuator endpoints
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
    info:
      enabled: true
  info:
    git:
      mode: full
info:
  app:
    name: "SynthexIt"
    description: "platforme de recrutement"
    version: 1.0.0
    contact:
      name: MOHAMED SAID TALEB
      email: mohamedsaidtaleb8@gmail.com
    url_exclusions_logging: /metrics, /prometheus, /health, /v3/api-docs, /webjars


backend:
  maxConnections: 600
  acquireTimeout: 1000
  auth:
    baseUrl: http://localhost:8083
    connectTimeout: 3000
    readTimeout: 3000
    writeTimeout: 3000
    responseTimeout: 3000