server:
  port: 8080
spring:
  application:
    name: api-gateway
  jetty:
    threads:
      max: '1000'
  tomcat:
    threads:
      max: '1000'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"
# Actuator Prometheus Endpoint
management:
    endpoints:
      web:
        exposure:
          include: prometheus
