server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

        - id: candidate-service
          uri: lb://CANDIDATE-SERVICE
          predicates:
            - Path=/candidate/**
          filters:
            - AuthenticationFilter

        - id: employer-service
          uri: lb://EMPLOYER-SERVICE
          predicates:
            - Path=/employer/**
          filters:
            - AuthenticationFilter

  application:
    name: api-gateway
  jetty:
    threads:
      max: '1000'
  tomcat:
    threads:
      max: '1000'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"
# Actuator Prometheus Endpoint
management:
    endpoints:
      web:
        exposure:
          include: "*"
backend:
  maxConnections: 600
  acquireTimeout: 1000
  auth:
    baseUrl: http://localhost:8083
    connectTimeout: 10000
    readTimeout: 10000
    writeTimeout: 10000
    responseTimeout: 10000
