server:
  port: 8082
spring:
  application:
    name: candidate-service
# PostgreSQL Data Source Configuration
  r2dbc:
        url: r2dbc:postgresql://localhost:5432/candidatedatabase
        username: myuser
        password: mypassword
  jpa:
        hibernate:
          ddl-auto: update
  sql:
        init:
          continue-on-error: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
backend:
  maxConnections: 600
  acquireTimeout: 1000
  employer:
    baseUrl: http://localhost:8081
    connectTimeout: 3000
    readTimeout: 3000
    writeTimeout: 3000
    responseTimeout: 3000