server:
  port: 8081
spring:
  application:
    name: employer-service
# PostgreSQL Data Source Configuration
  r2dbc:
        url: r2dbc:postgresql://localhost:5432/employerdatabase
        username: myuser
        password: mypassword
  jpa:
        hibernate:
          ddl-auto: create
  sql:
        init:
          continue-on-error: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
backend:
  maxConnections: 600
  acquireTimeout: 1000
  candidate:
    baseUrl: http://localhost:8082
    connectTimeout: 3000
    readTimeout: 3000
    writeTimeout: 3000
    responseTimeout: 3000