# Global Configuration
server:
  port: 8081
spring:
  application:
    name: employer-service
# PostgreSQL Data Source Configuration
  r2dbc:
        url: r2dbc:postgresql://localhost:5432/employerdatabase
        username: myuser
        password: mypassword
  jpa:
        hibernate:
          ddl-auto: update
  sql:
        init:
          continue-on-error: true
info:
  app:
    name: employer-service
    version: 1.0.0
# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  info:
    git:
      mode: full
  endpoint:
    prometheus:
      enabled: 'true'
    health:
      show-details: always
      enabled: 'true'
    info:
      enabled: 'true'

# Twilo configuration
twilio:
  account_sid: AC4740****************
  auth_token: af2359*****************
  trial_number: +185*****************

# Discovery Service Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Backend Configuration
backend:
  maxConnections: 600
  acquireTimeout: 1000
  candidate:
    baseUrl: http://localhost:8082
    connectTimeout: 3000
    readTimeout: 3000
    writeTimeout: 3000
    responseTimeout: 3000