server:
  port: 8083
spring:
  application:
    name: authentication-service
# PostgreSQL Data Source Configuration
  datasource:
        url: jdbc:postgresql://localhost:5432/authenticationDataBase
        username: myuser
        password: mypassword
  jpa:
        hibernate:
          ddl-auto: create
  sql:
        init:
          continue-on-error: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
